spring.application.name=api

# -
# MySQL
# -
spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=caio

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# nos codigos abaixo eu consigo mudar o nome dos parametros na url das requisições, mas vou deixar comentado:
#spring.data.web.pageable.page-parameter=pagina
#spring.data.web.pageable.size-parameter=tamanho
#spring.data.web.sort.sort-parameter=ordem

# EXEMPLO DE USO: http://localhost:8080/medicos?tamanho=5&pagina=1&ordem=email,desc

spring.web.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:1234578}